import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsString, IsNotEmpty, IsOptional, IsEmail } from 'class-validator';

export class CreateAdminsDto {
  @ApiPropertyOptional({
    description: 'UUID of the admin (auto-generated by the server)',
  })
  @IsOptional()
  @IsString()
  user_id?: string;

  @ApiProperty({ description: 'Full name of the admin' })
  @IsString()
  @IsNotEmpty()
  full_name: string;

  @ApiProperty({ description: 'Email address of the admin' })
  @IsEmail()
  email: string;

  @ApiPropertyOptional({
    description: 'Creation timestamp in ISO format (auto-generated by the server)',
    example: '2025-11-01T20:55:00Z',
  })
  @IsOptional()
  @IsString()
  created_at?: string;
}
