import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsString, IsNotEmpty, IsOptional, IsNumber } from 'class-validator';

export class CreateProductsDto {
  @ApiPropertyOptional({
    description: 'UUID of the product (auto-generated by the server)',
  })
  @IsOptional()
  @IsString()
  product_id?: string;

  @ApiProperty({ description: 'Name of the product', example: 'Popcorn Small' })
  @IsString()
  @IsNotEmpty()
  name: string;

  @ApiProperty({ description: 'Category of the product', example: 'food' })
  @IsString()
  @IsNotEmpty()
  category: string;

  @ApiProperty({ description: 'Price of the product', example: 100000 })
  @IsNumber()
  @IsNotEmpty()
  price: number;

  @ApiProperty({ description: 'Image URL of the product' })
  @IsString()
  @IsNotEmpty()
  image: string;

  @ApiPropertyOptional({
    description: 'Creation timestamp in ISO format (auto-generated by the server)',
    example: '2025-11-01T20:55:00Z',
  })
  @IsOptional()
  @IsString()
  created_at?: string;
}
